{pkgs, ...}: {
  environment.systemPackages = with pkgs.python310Packages; [
    altair
    beautifulsoup4
    bokeh
    catboost
    google-cloud-bigquery
    ibm-watson
    ipython
    jedi
    jedi-language-server
    jupyterhub
    jupyterlab
    keras
    lightgbm
    matplotlib
    mayavi
    networkx
    nltk
    numpy
    pandas
    pip
    plotly
    plotnine
    pynvim
    pyzmq
    requests
    scikit-learn
    scipy
    seaborn
    spyder
    statsmodels
    tableaudocumentapi
    tensorflow
    tensorflow-metadata
    tensorflow-probability
    trfl
    virtualenv
    virtualenvwrapper
    #torch
    #torchaudio-bin
    #torchvision
  ];
}
