{pkgs, ...}: {
  environment.systemPackages = with pkgs.rPackages; [
    Cairo
    DT
    DataExplorer
    #Hmisc #failed to compiling
    RColorBrewer
    XML
    #arrow #failed to compiling
    beepr
    colourpicker
    dataCompareR
    data_table
    datapasta
    devtools
    diffobj
    dplyr
    dygraphs
    echarts4r
    esquisse
    flexdashboard
    forecast
    fst
    geofacet
    # ggforce #failed to compiling
    ggiraph
    ggplot2
    githubinstall
    glue
    gmodels
    googleAnalyticsR
    googleAuthR
    gridExtra
    here
    httr
    installr
    janitor
    jsonlite
    knitr
    leaflet
    listviewer
    lme4
    lubridate
    magrittr
    mapsapi
    officer
    openxlsx
    optparse
    pacman
    paletteer
    patchwork
    plotly
    plumber
    profvis
    # prophet # r-stan failed to compiling
    purrr
    quantmod
    reactable
    readr
    remedy
    remotes
    reshape2
    reticulate
    rio
    rmarkdown
    roxygen2
    rvest
    scales
    sf
    shiny
    shinyjs
    spatstat
    splitstackshape
    sqldf
    stringr
    testthat
    tidycensus
    tidygeocoder
    tidymodels
    tidyquant
    tidyr
    tidytext
    tidyxl
    # tmap # r-terra, r-raster, r-leafem, leaflet failed to compiling
    # tmaptools
    tsbox
    usethis
    validate
    vroom
    yaml
    ymlthis
    zoo
  ];
}
